// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuGo0WIcuVltvmttchCt-StQDPvXtV80',
    appId: '1:272745497278:web:5e70e948a3b71cda7794ef',
    messagingSenderId: '272745497278',
    projectId: 'wall-d-fcc76',
    authDomain: 'wall-d-fcc76.firebaseapp.com',
    databaseURL: 'https://wall-d-fcc76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wall-d-fcc76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4qdIw0JxmgZJzo9lWLKP62N4i-_9Eqc',
    appId: '1:272745497278:android:538512854c58fbab7794ef',
    messagingSenderId: '272745497278',
    projectId: 'wall-d-fcc76',
    databaseURL: 'https://wall-d-fcc76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wall-d-fcc76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoSa3laqnShMxxORF_hQq7GvYO0gb3caI',
    appId: '1:272745497278:ios:635ef9197be82e587794ef',
    messagingSenderId: '272745497278',
    projectId: 'wall-d-fcc76',
    databaseURL: 'https://wall-d-fcc76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wall-d-fcc76.firebasestorage.app',
    iosClientId: '272745497278-i1l9q3r1mi6e0vc1ggtgshlqn7mjcjlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.walldFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoSa3laqnShMxxORF_hQq7GvYO0gb3caI',
    appId: '1:272745497278:ios:635ef9197be82e587794ef',
    messagingSenderId: '272745497278',
    projectId: 'wall-d-fcc76',
    databaseURL: 'https://wall-d-fcc76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wall-d-fcc76.firebasestorage.app',
    iosClientId: '272745497278-i1l9q3r1mi6e0vc1ggtgshlqn7mjcjlj.apps.googleusercontent.com',
    iosBundleId: 'com.example.walldFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtuGo0WIcuVltvmttchCt-StQDPvXtV80',
    appId: '1:272745497278:web:a251ae5cafedf1077794ef',
    messagingSenderId: '272745497278',
    projectId: 'wall-d-fcc76',
    authDomain: 'wall-d-fcc76.firebaseapp.com',
    databaseURL: 'https://wall-d-fcc76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wall-d-fcc76.firebasestorage.app',
  );
}
